#!/usr/bin/env python3
"""Generate packed, anti-aliased aircraft rotation masks for the firmware."""

from __future__ import annotations

import math
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "assets" / "icons"
OUTPUT = ROOT / "src" / "aircraft_icon_data.inc"
ANGLE_STEP_DEGREES = 5
ANGLE_COUNT = 360 // ANGLE_STEP_DEGREES
SUPERSAMPLE = 4

ICONS = (
    ("PlaneSmall", ASSET_DIR / "aircraft-yellow-source.png", 15),
    ("PlaneNormal", ASSET_DIR / "aircraft-yellow-source.png", 20),
    ("PlaneLarge", ASSET_DIR / "aircraft-yellow-source.png", 25),
    ("Helicopter", ASSET_DIR / "helicopter-yellow-source.png", 20),
)


def canvas_size_for(icon_size: int) -> int:
    size = math.ceil(icon_size * math.sqrt(2.0))
    return size if size % 2 else size + 1


def packed_frames(source_path: Path, icon_size: int) -> tuple[int, int, bytes]:
    source_alpha = Image.open(source_path).convert("RGBA").getchannel("A")
    canvas_size = canvas_size_for(icon_size)
    high_canvas_size = canvas_size * SUPERSAMPLE
    high_icon_size = icon_size * SUPERSAMPLE
    icon = source_alpha.resize(
        (high_icon_size, high_icon_size),
        Image.Resampling.LANCZOS,
    )
    base = Image.new("L", (high_canvas_size, high_canvas_size), 0)
    offset = (high_canvas_size - high_icon_size) // 2
    base.paste(icon, (offset, offset))

    frame_bytes = (canvas_size * canvas_size + 1) // 2
    output = bytearray()
    for frame_index in range(ANGLE_COUNT):
        angle = -frame_index * ANGLE_STEP_DEGREES
        rotated = base.rotate(
            angle,
            resample=Image.Resampling.BICUBIC,
            expand=False,
            fillcolor=0,
        )
        downsampled = rotated.resize(
            (canvas_size, canvas_size),
            Image.Resampling.LANCZOS,
        )
        alpha4 = [
            min(15, (value + 8) // 17)
            for value in downsampled.get_flattened_data()
        ]
        frame = bytearray(frame_bytes)
        for pixel_index, value in enumerate(alpha4):
            if pixel_index & 1:
                frame[pixel_index // 2] |= value
            else:
                frame[pixel_index // 2] = value << 4
        output.extend(frame)
    return canvas_size, frame_bytes, bytes(output)


def format_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t k{name}Frames[] PROGMEM = {{"]
    for start in range(0, len(data), 16):
        chunk = data[start : start + 16]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    sections = [
        "// Generated by scripts/build_aircraft_icons.py. Do not edit manually.",
        "namespace AircraftIconData {",
        f"static constexpr uint8_t kAngleStepDegrees = {ANGLE_STEP_DEGREES};",
        f"static constexpr size_t kAngleCount = {ANGLE_COUNT};",
    ]
    for name, path, icon_size in ICONS:
        canvas_size, frame_bytes, data = packed_frames(path, icon_size)
        sections.extend(
            (
                f"static constexpr uint8_t k{name}CanvasSize = {canvas_size};",
                f"static constexpr size_t k{name}FrameBytes = {frame_bytes};",
                format_array(name, data),
            )
        )
    sections.append("} // namespace AircraftIconData")
    OUTPUT.write_text("\n\n".join(sections) + "\n", encoding="ascii")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
